"""Remove title from day table and add title to cycle table

Revision ID: a8f80d02bb51
Revises: 
Create Date: 2024-01-28 15:16:49.318021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f80d02bb51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))

    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('cycle', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
